Traceback (most recent call last):
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/clemens10/miniconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/clemens10/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
latencies = []
runs = 0

while runs < 100:
    runs += 1
    with das.utils.Timer() as dt:
        d = next(mike)  # get a new chunk
        d = d[np.newaxis, ...]
        out = model.predict(d, verbose=0)  # run inference on the chunk
        # detect pulse and sine
        result = report_song(out[0, ...], pulse_index, sine_index)
        # print(result)
    latencies.append(dt.elapsed * 1000)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-4368a6a435da>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m     [0;32mwith[0m [0mdas[0m[0;34m.[0m[0mutils[0m[0;34m.[0m[0mTimer[0m[0;34m([0m[0;34m)[0m [0;32mas[0m [0mdt[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m         [0md[0m [0;34m=[0m [0mnext[0m[0;34m([0m[0mmike[0m[0;34m)[0m  [0;31m# get a new chunk[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m         [0md[0m [0;34m=[0m [0md[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0mnewaxis[0m[0;34m,[0m [0;34m...[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m         [0mout[0m [0;34m=[0m [0mmodel[0m[0;34m.[0m[0mpredict[0m[0;34m([0m[0md[0m[0;34m,[0m [0mverbose[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m  [0;31m# run inference on the chunk[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m         [0;31m# detect pulse and sine[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable

